# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'ASoC'
    applications: '85d8ec91-bc9d-48d8-9435-c42843fc831b'
    scanname: 'First'
    scantype: 'static'
    scanloc: 'SimpleIOT-Maven'

